	tilepal 0, GRAY, BROWN, BROWN, RED, GREEN, GREEN, GRAY, RED
	tilepal 0, RED, RED, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GRAY, BROWN, GRAY, BROWN, BROWN
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, RED, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, RED, RED, WATER, YELLOW, BROWN
	tilepal 0, BROWN, YELLOW, YELLOW, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, WATER, WATER, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, WATER, WATER, BROWN, BROWN, GRAY, GRAY
	tilepal 0, WATER, GRAY, GRAY, BROWN, BROWN, BROWN, GRAY, WATER
	tilepal 0, BROWN, BROWN, BROWN, GRAY, BROWN, BROWN, GRAY, BROWN
	tilepal 0, BROWN, GREEN, GRAY, GRAY, BROWN, BROWN, GREEN, GREEN

rept 16
	db $ff
endr

	tilepal 1, GREEN, GREEN, GRAY, GRAY, BROWN, BROWN, GRAY, BROWN
	tilepal 1, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, GRAY, GREEN
	tilepal 1, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, GRAY, BROWN
	tilepal 1, BROWN, GRAY, GRAY, BROWN, BROWN, GREEN, BROWN, BROWN
	tilepal 1, GREEN, GREEN, BROWN, BROWN, BROWN, GRAY, BROWN, BROWN
	tilepal 1, BROWN, BROWN, GRAY, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, GREEN, GREEN, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, BROWN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN
	tilepal 1, BROWN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
